#	$NetBSD: Makefile,v 1.1 2015/01/22 17:49:41 christos Exp $

SUBDIR=rc.d

FILESDIR=               /usr/share/examples/blocklist
FILESMODE=    644
FILES=	blocklistd.conf

.include <bsd.files.mk>
.include <bsd.subdir.mk>
