#	$NetBSD: Makefile,v 1.3 2015/01/26 00:18:40 christos Exp $

SUBDIR=rc.d

FILESDIR=               /usr/share/examples/blocklist
FILESMODE=    644
FILES=	blocklistd.conf npf.conf

.include <bsd.files.mk>
.include <bsd.subdir.mk>
